# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '\u5b66\u751f\u4fe1\u606f'},
        ),
    ]
